### ISSUE TITLE
Checklist for `next`

### ISSUE THREAD

**Issue by calebeby** [cloudfour/lighthouse-parade#117]
We are working on a new big release! There are lots of changes, and I'm keeping track of them here:

- [x] New CSV output writer (#111)
- [x] Use Lighthouse Node API instead of CLI (#111)
- [x] Rename `--ignore-robots` to `--ignore-robots-txt` (#111)
- [ ] Set up bundling (#116)
- [ ] Output directly to Google Sheets
- [ ] Investigate taking out `simplecrawler` and instead finding links directly in the page HTML which lighthouse returns
- [ ] Add flags for enabling/disabling different lighthouse categories
- [ ] Allow averaging multiple lighthouse runs
- [ ] Update documentation
- [ ] Update all dependencies
- [ ] Set up a static test suite
- [ ] Write changesets
