### ISSUE TITLE
Set up GitHub Action

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/lighthouse-parade#6]
We eventually want to set up a GitHub Action to run CI tests whenever new commits are pushed.

- [x] add/configure the workflow (#12)
- [x] npm run test (#12)
- [ ] ~npm run type~ (#13)
- [ ] ~npm run check-lint~ (#14)
